In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
service_obj = Service(r"D:\C Drive\Program Files\chromedriver-win64\chromedriver.exe")

driver = webdriver.Chrome(service = service_obj)
from selenium.webdriver.common.by import By
import time

In [2]:
driver.get("https://www.linkedin.com/home")

In [3]:
mail = "Sazzad.hossain3.cse@ulab.edu.bd"
password = "killer_009"

In [4]:
driver.find_element(By.XPATH, "//input[@type='text']").send_keys(mail)
driver.find_element(By.XPATH, "//input[@type='password']").send_keys(password)
driver.find_element(By.XPATH, "//button[@type='submit']").click()

In [5]:
# UK
driver.get("https://www.linkedin.com/jobs/search/?currentJobId=3724469257&geoId=101165590&location=United%20Kingdom&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&refresh=true&sortBy=R")

In [6]:
import pandas as pd
df = pd.DataFrame()
ljob_title =[]
lname_location =[]
ljob_description =[]

In [9]:
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException, TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

page = 1
consecutive_timeout_exceptions = 0

while True:
    print(page)
    try:
        # Increase the timeout to make sure the element is located
        page_numbers = WebDriverWait(driver, 20).until(
            EC.element_to_be_clickable((By.XPATH, f"//button[@aria-label='Page {page}']"))
        )
        page_numbers.click()
        time.sleep(3)

        # Using "find_elements" for searching multiple elements
        jobs_block = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.XPATH, "//ul[@class='scaffold-layout__list-container']/li"))
        )

        # executes JS to scroll the job divs into view
        for job in jobs_block:
            driver.execute_script("arguments[0].scrollIntoView();", job)
            time.sleep(1)

        jobs_link = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.XPATH, "//ul[@class='scaffold-layout__list-container']/li/div/div/div[1]/div[2]/div[1]/a"))
        )

        for link in jobs_link:
            while True:
                try:
                    link.click()
                    time.sleep(1)

                    job_title = WebDriverWait(driver, 10).until(
                        EC.presence_of_element_located((By.XPATH, "//h2[@class='t-24 t-bold job-details-jobs-unified-top-card__job-title']"))
                    ).text

                    name_location = WebDriverWait(driver, 10).until(
                        EC.presence_of_element_located((By.XPATH, "//div[@class='job-details-jobs-unified-top-card__primary-description']"))
                    ).text

                    job_description = WebDriverWait(driver, 10).until(
                        EC.presence_of_element_located((By.XPATH, "//div[@id='job-details']"))
                    ).text

                    ljob_title.append(job_title)
                    lname_location.append(name_location)
                    ljob_description.append(job_description)
                    break  # Successfully clicked and collected data, so break out of the loop
                except ElementClickInterceptedException:
                    print("Element is not clickable. Retrying...")
                    # Add additional handling here, e.g., scroll to the element
                    driver.execute_script("arguments[0].scrollIntoView();", link)
                    
        # Increment the page number
        page += 1

        # Reset consecutive_timeout_exceptions counter
        consecutive_timeout_exceptions = 0

    except NoSuchElementException as e:
        print(f"Error: {str(e)}")
        traceback.print_exc()
        if "Unable to locate element" in str(e):
            print(f"No more pages after page {page}")
            break
    except TimeoutException as e:
        consecutive_timeout_exceptions += 1
        print(f"TimeoutException: {str(e)} (Consecutive: {consecutive_timeout_exceptions})")
        if consecutive_timeout_exceptions >= 3:
            print("Exceeded consecutive timeout exceptions limit. Exiting.")
            break
        # Handle the TimeoutException here, e.g., refresh the page
        driver.refresh()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
TimeoutException: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF65DE17D32+55474]
	(No symbol) [0x00007FF65DD877E2]
	(No symbol) [0x00007FF65DC3E0EB]
	(No symbol) [0x00007FF65DC7EBAC]
	(No symbol) [0x00007FF65DC7ED2C]
	(No symbol) [0x00007FF65DCB9F77]
	(No symbol) [0x00007FF65DC9F19F]
	(No symbol) [0x00007FF65DCB7EF2]
	(No symbol) [0x00007FF65DC9EF33]
	(No symbol) [0x00007FF65DC73D41]
	(No symbol) [0x00007FF65DC74F84]
	GetHandleVerifier [0x00007FF65E17B772+3609330]
	GetHandleVerifier [0x00007FF65E1D1A90+3962384]
	GetHandleVerifier [0x00007FF65E1C9F1F+3930783]
	GetHandleVerifier [0x00007FF65DEB3CC6+694342]
	(No symbol) [0x00007FF65DD92238]
	(No symbol) [0x00007FF65DD8E4A4]
	(No symbol) [0x00007FF65DD8E5D2]
	(No symbol) [0x00007FF65DD7EE33]
	BaseThreadInitThunk [0x00007FFA1A967344+20]
	RtlUserThreadStart [0x00007FFA1C8426B1+33]
 (Consecutive: 1)
41
TimeoutException: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF65DE17D32+55474]
	(No symbol) [0x00007FF65DD877E2]
	(No symbol) [0x00007FF65DC3E0EB]
	(No symbol) [0x00007FF65DC7EBAC]
	(No symbol) [0x00007FF65DC7ED2C]
	(No symbol) [0x00007FF65DCB9F77]
	(No symbol) [0x00007FF65DC9F19F]
	(No symbol) [0x00007FF65DCB7EF2]
	(No symbol) [0x00007FF65DC9EF33]
	(No symbol) [0x00007FF65DC73D41]
	(No symbol) [0x00007FF65DC74F84]
	GetHandleVerifier [0x00007FF65E17B772+3609330]
	GetHandleVerifier [0x00007FF65E1D1A90+3962384]
	GetHandleVerifier [0x00007FF65E1C9F1F+3930783]
	GetHandleVerifier [0x00007FF65DEB3CC6+694342]
	(No symbol) [0x00007FF65DD92238]
	(No symbol) [0x00007FF65DD8E4A4]
	(No symbol) [0x00007FF65DD8E5D2]
	(No symbol) [0x00007FF65DD7EE33]
	BaseThreadInitThunk [0x00007FFA1A967344+20]
	RtlUserThreadStart [0x00007FFA1C8426B1+33]
 (Consecutive: 2)
41
TimeoutException: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF65DE17D32+55474]
	(No symbol) [0x00007FF65DD877E2]
	(No symbol) [0x00007FF65DC3E0EB]
	(No symbol) [0x00007FF65DC7EBAC]
	(No symbol) [0x00007FF65DC7ED2C]
	(No symbol) [0x00007FF65DCB9F77]
	(No symbol) [0x00007FF65DC9F19F]
	(No symbol) [0x00007FF65DCB7EF2]
	(No symbol) [0x00007FF65DC9EF33]
	(No symbol) [0x00007FF65DC73D41]
	(No symbol) [0x00007FF65DC74F84]
	GetHandleVerifier [0x00007FF65E17B772+3609330]
	GetHandleVerifier [0x00007FF65E1D1A90+3962384]
	GetHandleVerifier [0x00007FF65E1C9F1F+3930783]
	GetHandleVerifier [0x00007FF65DEB3CC6+694342]
	(No symbol) [0x00007FF65DD92238]
	(No symbol) [0x00007FF65DD8E4A4]
	(No symbol) [0x00007FF65DD8E5D2]
	(No symbol) [0x00007FF65DD7EE33]
	BaseThreadInitThunk [0x00007FFA1A967344+20]
	RtlUserThreadStart [0x00007FFA1C8426B1+33]
 (Consecutive: 3)
Exceeded consecutive timeout exceptions limit. Exiting.

In [10]:
data = {"job_title" :ljob_title, "name_location" : lname_location, "job_description": ljob_description}

df = pd.DataFrame(data)
print(df)

                                        job_title  \
0                              Adult Psychiatrist
1           Culinary Lead, Chipotle International
2               Chief Tornado Structural Engineer
3     Territory Sales Manager DACH & North Europe
4       Graduate/Junior Machine Learning Engineer
...                                           ...
1008                          Warehouse Operative
1009                 Retail Assistant - Part Time
1010                           Teaching Assistant
1011                               Support Worker
1012              SEND Teaching Assistant Walsall

                                          name_location  \
0     Interact Medical Ltd · Nottinghamshire, Englan...
1     Chipotle Mexican Grill · Marylebone, England, ...
2     BAE Systems · Samlesbury, England, United King...
3     Oxford Instruments plc · DACH  4 days ago  · 4...
4     IT Graduate · City of London, England, United ...
...                                                 ...
1008  Devyani International P Ltd · Motherwell, Scot...
1009  The Range · West Midlands, England, United Kin...
1010  Reeson Education · Sunbury-on-Thames, England,...
1011  Creative Support · Grimsby, England, United Ki...
1012  Aspire People · Metropolitan Borough of Walsal...

                                        job_description
0     About the job\nGeneral adult Consultant Psychi...
1     About the job\nCulinary Lead, Chipotle Interna...
2     About the job\nStructural Engineer\n\nLocation...
3     About the job\nWe are looking for a Territory ...
4     About the job\nThis job is sourced from a job ...
...                                                 ...
1008  About the job\nThis job is sourced from a job ...
1009  About the job\nThis job is sourced from a job ...
1010  About the job\nThis job is sourced from a job ...
1011  About the job\nThis job is sourced from a job ...
1012  About the job\nThis job is sourced from a job ...

[1013 rows x 3 columns]

In [11]:
df

,job_title,name_location,job_description
0,Adult Psychiatrist,"Interact Medical Ltd · Nottinghamshire, Englan...",About the job\nGeneral adult Consultant Psychi...
1,"Culinary Lead, Chipotle International","Chipotle Mexican Grill · Marylebone, England, ...","About the job\nCulinary Lead, Chipotle Interna..."
2,Chief Tornado Structural Engineer,"BAE Systems · Samlesbury, England, United King...",About the job\nStructural Engineer\n\nLocation...
3,Territory Sales Manager DACH & North Europe,Oxford Instruments plc · DACH 4 days ago · 4...,About the job\nWe are looking for a Territory ...
4,Graduate/Junior Machine Learning Engineer,"IT Graduate · City of London, England, United ...",About the job\nThis job is sourced from a job ...
...,...,...,...
1008,Warehouse Operative,"Devyani International P Ltd · Motherwell, Scot...",About the job\nThis job is sourced from a job ...
1009,Retail Assistant - Part Time,"The Range · West Midlands, England, United Kin...",About the job\nThis job is sourced from a job ...
1010,Teaching Assistant,"Reeson Education · Sunbury-on-Thames, England,...",About the job\nThis job is sourced from a job ...
1011,Support Worker,"Creative Support · Grimsby, England, United Ki...",About the job\nThis job is sourced from a job ...
1012,SEND Teaching Assistant Walsall,Aspire People · Metropolitan Borough of Walsal...,About the job\nThis job is sourced from a job ...

In [12]:
# Specify the file path where you want to save the CSV file
csv_file_path = 'JD_UnitedKingdom.csv'

# Write the DataFrame to a CSV file
df.to_csv(csv_file_path, index=False)

print(f"Data has been written to {csv_file_path}")

Data has been written to JD_UnitedKingdom.csv